//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Drawing;

namespace SwExportAddin.Properties {
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources() {
        }

        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("SwExportAddin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static Bitmap ExportPlano {
            get {
                object obj = ResourceManager.GetObject("ExportPlano", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap ExportCarpeta {
            get {
                object obj = ResourceManager.GetObject("ExportCarpeta", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        internal static Bitmap ExportSelect {
            get {
                object obj = ResourceManager.GetObject("ExportSelect", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
